name: d2l
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2020.12.8=hecd8cb5_0
  - certifi=2020.12.5=py38hecd8cb5_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1i=h9ed2024_0
  - pip=20.3.3=py38hecd8cb5_0
  - python=3.8.5=h26836e1_1
  - readline=8.0=h1de35cc_0
  - setuptools=51.0.0=py38hecd8cb5_2
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.11.0
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - cachetools==4.2.0
    - cffi==1.14.4
    - chardet==4.0.0
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - d2l==0.15.1
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dm-tree==0.1.5
    - entrypoints==0.3
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - ipykernel==5.4.2
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.5
    - numpy==1.19.4
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.8
    - pandas==1.1.5
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.1
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.8
    - protobuf==3.14.0
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.7.3
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pyzmq==20.0.0
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - send2trash==1.5.0
    - six==1.15.0
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - tensorflow-probability==0.11.1
    - termcolor==1.1.0
    - terminado==0.9.1
    - testpath==0.4.4
    - torch==1.7.1
    - torchvision==0.8.2
    - tornado==6.1
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
prefix: /Users/agupta/anaconda3/envs/d2l

